site_name: News Media Bias Plus
site_url: https://vectorinstitute.github.io/Newsmediabias-plus/
use_directory_urls: false

theme:
  name: material

nav:
    - Home: index.md
    
    - Datasets: dataset.md
    # - Annotation Framework: Annotation.md
    - HumaniBench: HumaniBench.md
    - VLDBench: VLDBench.md
    - Fairsense: Fairsense.md
    - Publications: Publications.md
    - About Us: About-us.md

