site_name: News Media Bias Plus
site_url: https://github.com/VectorInstitute/Newsmediabias-plus/tree/website-rewamp
use_directory_urls: false
theme: material  # You can choose another theme if preferred

nav:
    - Home: index.md
    
    - Datasets: dataset.md
    # - Annotation Framework: Annotation.md
    - HumaniBench: HumaniBench.md
    - VLDBench: VLDBench.md
    - Publications: Publications.md
    - About Us: About-us.md

