site_name: News Media Bias Plus
theme: material  # You can choose another theme if preferred

nav:
    - Home: index.md
    
    - Dataset: dataset.md
    - Annotation Framework: Annotation.md
    - Benchmarks: Benchmark.md
    - About Us: About-us.md
